language: java
jdk:
  - oraclejdk8

services:
    - postgresql

env:
  - BUILD_TOOL=maven

before_script:
  - psql -c "create database catwatch;" -U postgres -h localhost
  - psql -c "create database catwatch_test;" -U postgres -h localhost
  - psql -c "create user cat1 with password 'cat1';" -U postgres -h localhost

script:
  - ./build.sh
